ENG-362: parameterize production and development environments
xosphere/terraform-xosphere-instance-orchestrator pull request #8
Opened 2022-04-21 22:23 UTC by actarsky

2022-04-21 22:34 UTC, alanxo requested changes

2022-04-21 22:34 UTC, alanxo commented on main.tf
> -  api_token_arn = "arn:aws:secretsmanager:us-west-2:143723790106:secret:customer/${var.customer_id}"
Shouldn't this also use var.xo_account_id?

2022-04-21 22:34 UTC, alanxo commented on main.tf
> -  endpoint_url = "https://portal-api.xosphere.io/v1"
Should this also be a param that can be overwritten?

2022-04-21 22:34 UTC, alanxo commented on main.tf
> -  endpoint_url = "https://portal-api.xosphere.io/v1"
I see a var was added, in that case should this be removed?

2022-04-21 22:34 UTC, alanxo commented on main.tf
> +
Is this whitespace intentional?

2022-04-21 22:34 UTC, alanxo commented on main.tf
> +
Is this whitespace intentional?

2022-04-22 00:09 UTC, closed without merging

2022-04-22 00:11 UTC, actarsky commented
something bad happened with this pull request - opened #9 instead